### ISSUE TITLE
Do you have to cycle through the tabs?

### ISSUE THREAD

**Issue by drew-wallace** [eamodio/vscode-restore-editors#1]
Just curious. I'm sure it would be faster to not do that.

Great extension by the way. It really helps when switching branches where the current editors don't exist.

**Comment by eamodio** [comment]
@drew-wallace sadly I do have to cycle through the tabs. It is because vscode doesn't provide any api that gets at the open editors -- and I can hack it by creating my own list, by cycling through and trapping when the active one changes. I haven't found a better solution - but there is an [open issue](https://github.com/Microsoft/vscode/issues/15178) against vscode to support an api for this.

**Comment by eamodio** [comment]
Resolved in 1.0
