### ISSUE TITLE
Feature request: save editors by name, and show in sidebar

### ISSUE THREAD

**Issue by lonix1** [eamodio/vscode-restore-editors#4]
Idea:
- Add a sidebar icon
- When clicked shows a list of saved sets of editors
- Each set has a name
- Click an entry to open all those editors
- Button to delete an entry

**Comment by eamodio** [comment]
Unfortunately since vscode **still** has no editor tab api this extension is very hacky and thus I don't want to put too much effort into it because it is so fragile. See my comment here: https://github.com/eamodio/vscode-restore-editors/issues/3#issuecomment-303853084

But as soon as vscode adds a proper editor tabs api I would be very happy to add many more features.

**Comment by lonix1** [comment]
I upvoted that issue.

**Comment by xmedeko** [comment]
What about [VSCode-Tab-Groups](/usama8800/VSCode-Tab-Groups)? It has a side bar icon with the list of saved tabs - editors.

**Comment by lonix1** [comment]
@eamodio Does the new tabs API help?

**Comment by eamodio** [comment]
Resolved in 1.0
